FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app

COPY pom.xml .

COPY src ./src

RUN mvn package -DskipTests

FROM eclipse-temurin:21-jre-jammy
WORKDIR /app

COPY --from=build /app/target/report_central-0.0.1-SNAPSHOT.jar app.jar

ENV SERVER_PORT=8090
EXPOSE 8090

ENTRYPOINT ["java", "-jar", "app.jar"]